"""create er_ditagram table

Revision ID: 2457ab02df6a
Revises: e803d01ebebb
Create Date: 2025-07-07 02:34:23.801765

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql


# revision identifiers, used by Alembic.
revision: str = '2457ab02df6a'
down_revision: Union[str, Sequence[str], None] = 'e803d01ebebb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('er_diagrams',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('user_id', mysql.CHAR(collation='utf8mb4_unicode_ci', length=36), nullable=False),
    sa.Column('name', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_er_diagrams_id'), 'er_diagrams', ['id'], unique=False)
    op.create_index(op.f('ix_er_diagrams_name'), 'er_diagrams', ['name'], unique=False)
    op.create_index(op.f('ix_er_diagrams_project_id'), 'er_diagrams', ['project_id'], unique=False)
    op.create_index(op.f('ix_er_diagrams_user_id'), 'er_diagrams', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_er_diagrams_user_id'), table_name='er_diagrams')
    op.drop_index(op.f('ix_er_diagrams_project_id'), table_name='er_diagrams')
    op.drop_index(op.f('ix_er_diagrams_name'), table_name='er_diagrams')
    op.drop_index(op.f('ix_er_diagrams_id'), table_name='er_diagrams')
    op.drop_table('er_diagrams')
    # ### end Alembic commands ###
