"""added tables branches and commits

Revision ID: 952db6e68c11
Revises: 2457ab02df6a
Create Date: 2025-07-07 12:45:56.854963

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '952db6e68c11'
down_revision: Union[str, Sequence[str], None] = '2457ab02df6a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('branches',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('er_diagram_id', sa.Integer(), nullable=False),
    sa.Column('user_id', mysql.CHAR(collation='utf8mb4_unicode_ci', length=36), nullable=False),
    sa.Column('name', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['er_diagram_id'], ['er_diagrams.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_branches_er_diagram_id'), 'branches', ['er_diagram_id'], unique=False)
    op.create_index(op.f('ix_branches_id'), 'branches', ['id'], unique=False)
    op.create_index(op.f('ix_branches_name'), 'branches', ['name'], unique=False)
    op.create_index(op.f('ix_branches_user_id'), 'branches', ['user_id'], unique=False)
    op.create_table('commits',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('branch_id', sa.Integer(), nullable=False),
    sa.Column('user_id', mysql.CHAR(collation='utf8mb4_unicode_ci', length=36), nullable=False),
    sa.Column('body', mysql.JSON(), nullable=False),
    sa.Column('comment', sa.Text(collation='utf8mb4_unicode_ci'), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['branch_id'], ['branches.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_commits_branch_id'), 'commits', ['branch_id'], unique=False)
    op.create_index(op.f('ix_commits_id'), 'commits', ['id'], unique=False)
    op.create_index(op.f('ix_commits_user_id'), 'commits', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('commits_ibfk_1', 'commits', type_='foreignkey')
    op.drop_constraint('commits_ibfk_2', 'commits', type_='foreignkey')
    op.drop_index(op.f('ix_commits_user_id'), table_name='commits')
    op.drop_index(op.f('ix_commits_id'), table_name='commits')
    op.drop_index(op.f('ix_commits_branch_id'), table_name='commits')
    op.drop_table('commits')
    op.drop_constraint('branches_ibfk_1', 'branches', type_='foreignkey')
    op.drop_constraint('branches_ibfk_2', 'branches', type_='foreignkey')
    op.drop_index(op.f('ix_branches_user_id'), table_name='branches')
    op.drop_index(op.f('ix_branches_name'), table_name='branches')
    op.drop_index(op.f('ix_branches_id'), table_name='branches')
    op.drop_index(op.f('ix_branches_er_diagram_id'), table_name='branches')
    op.drop_table('branches')
    # ### end Alembic commands ###
