"""create users table

Revision ID: dfd82cd869d1
Revises: 
Create Date: 2025-07-06 01:06:28.057991

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'dfd82cd869d1'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('personal_access_tokens',
    sa.Column('id', mysql.BIGINT(unsigned=True), autoincrement=True, nullable=False),
    sa.Column('tokenable_type', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=255), nullable=False),
    sa.Column('tokenable_id', mysql.BIGINT(unsigned=True), autoincrement=False, nullable=False),
    sa.Column('name', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=255), nullable=False),
    sa.Column('token', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=64), nullable=False),
    sa.Column('abilities', mysql.TEXT(collation='utf8mb4_unicode_ci'), nullable=True),
    sa.Column('last_used_at', mysql.TIMESTAMP(), nullable=True),
    sa.Column('expires_at', mysql.TIMESTAMP(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_unicode_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index(op.f('personal_access_tokens_tokenable_type_tokenable_id_index'), 'personal_access_tokens', ['tokenable_type', 'tokenable_id'], unique=False)
    op.create_index(op.f('personal_access_tokens_token_unique'), 'personal_access_tokens', ['token'], unique=True)
    op.create_table('roles',
    sa.Column('id', mysql.BIGINT(unsigned=True), autoincrement=True, nullable=False),
    sa.Column('name', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=255), nullable=False),
    sa.Column('guard_name', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_unicode_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index(op.f('roles_name_guard_name_unique'), 'roles', ['name', 'guard_name'], unique=True)
    op.create_table('model_has_roles',
    sa.Column('role_id', mysql.BIGINT(unsigned=True), autoincrement=False, nullable=False),
    sa.Column('model_type', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=255), nullable=False),
    sa.Column('model_id', mysql.BIGINT(unsigned=True), autoincrement=False, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], name=op.f('model_has_roles_role_id_foreign'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('role_id', 'model_id', 'model_type'),
    mysql_collate='utf8mb4_unicode_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index(op.f('model_has_roles_model_id_model_type_index'), 'model_has_roles', ['model_id', 'model_type'], unique=False)
    op.create_table('permissions',
    sa.Column('id', mysql.BIGINT(unsigned=True), autoincrement=True, nullable=False),
    sa.Column('name', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=255), nullable=False),
    sa.Column('guard_name', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_unicode_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index(op.f('permissions_name_guard_name_unique'), 'permissions', ['name', 'guard_name'], unique=True)
    op.create_table('role_has_permissions',
    sa.Column('permission_id', mysql.BIGINT(unsigned=True), autoincrement=False, nullable=False),
    sa.Column('role_id', mysql.BIGINT(unsigned=True), autoincrement=False, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['permission_id'], ['permissions.id'], name=op.f('role_has_permissions_permission_id_foreign'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], name=op.f('role_has_permissions_role_id_foreign'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('permission_id', 'role_id'),
    mysql_collate='utf8mb4_unicode_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('password_reset_tokens',
    sa.Column('email', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=255), nullable=False),
    sa.Column('token', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('email'),
    mysql_collate='utf8mb4_unicode_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('model_has_permissions',
    sa.Column('permission_id', mysql.BIGINT(unsigned=True), autoincrement=False, nullable=False),
    sa.Column('model_type', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=255), nullable=False),
    sa.Column('model_id', mysql.BIGINT(unsigned=True), autoincrement=False, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['permission_id'], ['permissions.id'], name=op.f('model_has_permissions_permission_id_foreign'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('permission_id', 'model_id', 'model_type'),
    mysql_collate='utf8mb4_unicode_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index(op.f('model_has_permissions_model_id_model_type_index'), 'model_has_permissions', ['model_id', 'model_type'], unique=False)
    op.create_table('users',
    sa.Column('id', mysql.CHAR(collation='utf8mb4_unicode_ci', length=36), nullable=False, comment='(DC2Type:guid)'),
    sa.Column('name', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=255), nullable=False),
    sa.Column('email', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=255), nullable=False),
    sa.Column('email_verified_at', mysql.TIMESTAMP(), nullable=True),
    sa.Column('password', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=255), nullable=False),
    sa.Column('remember_token', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_unicode_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index(op.f('users_email_unique'), 'users', ['email'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('users_email_unique'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('model_has_permissions_model_id_model_type_index'), table_name='model_has_permissions')
    op.drop_table('model_has_permissions')
    op.drop_index(op.f('permissions_name_guard_name_unique'), table_name='permissions')
    op.drop_table('password_reset_tokens')
    op.drop_table('role_has_permissions')
    op.drop_table('permissions')
    op.drop_index(op.f('model_has_roles_model_id_model_type_index'), table_name='model_has_roles')
    op.drop_table('model_has_roles')
    op.drop_index(op.f('roles_name_guard_name_unique'), table_name='roles')
    op.drop_table('roles')
    op.drop_index(op.f('personal_access_tokens_token_unique'), table_name='personal_access_tokens')
    op.drop_index(op.f('personal_access_tokens_tokenable_type_tokenable_id_index'), table_name='personal_access_tokens')
    op.drop_table('personal_access_tokens')
    # ### end Alembic commands ###
