version: "3.8"

services:
  web:
    build:
      context: ./php-fpm
      dockerfile: ../../../web/Dockerfile
    container_name: erhub-web
    user: "${UID}:${GID}"
    expose:
      - "9000"
    tty: true
    volumes:
      - ../../web:/app
    depends_on:
      - mysql

  api:
    build: ../../api
    container_name: erhub-api
    ports:
      - "8001:8000"
    volumes:
      - ../../api:/app
    depends_on:
      - mysql
    env_file:
      - .env

  mysql:
    image: mysql:8.0
    container_name: erhub-mysql
    ports:
      - '${DB_HOST_PORT}:3306'
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_USER: ${DB_USERNAME}
      MYSQL_PASSWORD: ${DB_PASSWORD}
    volumes:
      - db_data:/var/lib/mysql

  proxy:
    container_name: erhub-proxy
    image: nginx:1.25.4-alpine
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/ssl:/ssl
      - ./nginx/conf.d:/etc/nginx/conf.d
      - ./nginx/log:/var/log/nginx
      - ../../web/public:/var/www/erhub/public
    ports:
      - 80:80
      - 443:443

volumes:
  db_data:

networks:
  default:
    name: erhub
